version: '3.8'

services:
  # 1. Base de datos
  db:
    image: postgres:15-alpine
    container_name: postgres_rrhh
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: rrhh_db
    ports:
      - "5432:5432"
    volumes:
      - rrhh_data:/var/lib/postgresql/data

  # 2. Panel visual
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_rrhh
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@empresa.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. Backend (Orquestador FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mi-orquestador
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Usamos 'db' en el host porque Docker resuelve el nombre del servicio
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/rrhh_db
    depends_on:
      - db
    volumes:
      - ./backend:/app # Sincroniza tu código para que el --reload funcione

volumes:
  rrhh_data: