# 1. EL DEPLOYMENT (Las cajas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestador-deployment
spec:
  replicas: 2  # Crea 2 clones del sistema para soportar carga
  selector:
    matchLabels:
      app: orquestador
  template:
    metadata:
      labels:
        app: orquestador
    spec:
      containers:
      - name: orquestador
        image: orquestador-onboarding:latest
        imagePullPolicy: Never  # Usa la imagen local creada 
        ports:
        - containerPort: 8000
---
# 2. EL SERVICE (La entrada)
apiVersion: v1
kind: Service
metadata:
  name: orquestador-service
spec:
  type: LoadBalancer # Balanceador de carga entre los 2 clones
  selector:
    app: orquestador
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000